---
title: "Tariffs + Clean Energy"
output: html_document
date: "2025-04-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}

library(tidyverse)
library(reshape2)

```

```{r load data}

tariff_by_country <- data.frame(country = c("China", "European Union", "India", "Vietnam"), 
           Rate = c(1.04, 0.2, 0.27, 0.46))

tariff_by_country$labels <- paste0(tariff_by_country$Rate * 100, "%")

# please note that 2024 values are estimates taken from tables while other numbers were published on EIA's website: https://www.eia.gov/totalenergy/data/monthly/pdf/mer.pdf

energy_trade_us <- data.frame(year = c(2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024),
                              Consumption = c(93.9, 97.4, 96.6, 88.85, 93.36, 94.79, 93.59, 94.2),
                              Production = c(84.37, 91.96, 97.6, 91.86, 93.84, 98.53, 102.82, 103.2),
                              Imports = c(25.46, 24.83, 22.87, 19.99, 21.46, 21.51, 21.7, 21.66),
                              Exports = c(17.95, 21.22, 23.48, 23.46, 25.07, 27.33, 29.5, 30.9))

energy_trade_us <- melt(energy_trade_us, id.vars = "year")

energy_production_us <- data.frame(year = c(2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024),
                                   Coal = c(15.63, 15.36, 14.26, 10.7, 11.6, 12.04, 11.81, 10.41),
                                   `Natural Gas` = c(28.29, 31.88, 35.19, 35.06, 35.81, 37.56, 39.25, 39.18),
                                   `Crude Oil` = c(19.55, 22.81, 25.6, 23.57, 23.4, 24.71, 26.85, 27.52),
                                   NGPL = c(4.99, 5.73, 6.35, 6.8, 7.1, 7.74, 8.39, 9.1),
                                   Nuclear = c(8.42, 8.44, 8.45, 8.25, 8.13, 8.06, 8.10, 8.17),
                                   Renewables = c(7.5, 7.74, 7.75, 7.46, 7.81, 8.31, 8.43, 8.83))

energy_production_us <- melt(energy_production_us, id.vars = "year")

energy_production_us <- energy_production_us %>%
  group_by(year) %>%
  mutate(Percent = value / sum(value)) %>%
  mutate(labels = paste0(round(Percent*100, digits = 1), "%"))

energy_production_us$variable <- str_replace(energy_production_us$variable, "Crude.Oil", "Crude Oil")
energy_production_us$variable <- str_replace(energy_production_us$variable, "Natural.Gas", "Natural Gas")

color_0 <- "#f79500"
color_1 <- "#F0BD70" 
color_2 <- "#43938A"
color_3 <- "#2F6569"

```



```{r graphs}

tariff_by_country %>%
  ggplot(aes(x = reorder(country, Rate), y = Rate)) +
  geom_bar(stat = "identity", fill = color_3) +
  geom_text(aes(label = labels), hjust = 1.1, fontface = "bold", size = 7.5, family = "Georgia", color = "white") +
  coord_flip() +
  ggtitle("\nProposed Reciprocal Tariffs on\nTop Renewable Energy Producers") +
  labs(subtitle = "as of 12:00 PM on April 9, 2025", caption = "Source: The White House | github: julia-tache") +
  theme(plot.background = element_rect(fill = "#F5F5F5", color = NA),
        plot.margin = margin(0.25, 0.25, 0.25, 0.6, "cm"),
        panel.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.grid.major = element_line(color = "#F5F5F5"),
        panel.grid.minor = element_line(color = "#F5F5F5"),
        plot.title = element_text(size = 19, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 16, hjust = 0.5, face = "italic"),
        plot.caption = element_text(size = 12, face = "italic", hjust = 1),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 18, hjust = 1),
        axis.ticks = element_blank(),
        legend.position = "none",
        text = element_text(family = "Georgia", size = 13))

ggsave("tariff_by_country.png", height = 5, width = 8)

energy_trade_us %>%
  ggplot(aes(x = year, y = value, group = variable, color = variable)) +
  geom_point(size = 3) +
  geom_line(size = 1) +
  scale_color_manual(values = c(color_0, color_1, color_2, color_3)) +
  scale_x_continuous(breaks = c(2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024)) +
  scale_y_continuous(breaks = seq(10, 120,20)) +
  ggtitle("\nU.S. Production and Exports of Energy\novertook Consumption and Imports in 2019") +
  labs(subtitle = "quadrillion British Thermal Units", caption = "\nSource: U.S. Energy Information Administration | github: julia-tache") +
  ylab("Quads") +
  theme(plot.background = element_rect(fill = "#F5F5F5", color = NA),
        plot.margin = margin(0.25, 0.25, 0.25, 0.6, "cm"),
        panel.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.grid.major = element_line(color = "gray"),
        panel.grid.minor = element_line(color = "#F5F5F5"),
        plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 16, hjust = 0.5, face = "italic"),
        plot.caption = element_text(size = 12, face = "italic", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text.y = element_text(size = 14, hjust = 0),
        axis.ticks = element_blank(),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "#F5F5F5"),
        text = element_text(family = "Georgia", size = 13))

ggsave("energy_trade_us.png", height = 5, width = 8)

energy_production_us %>%
  ggplot(aes(x = year, y = Percent, fill = variable)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c(color_0, color_1, "#0D98BA", "#0c2d1c", color_2, color_3)) +
  scale_x_continuous(breaks = c(2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024)) +
  geom_text(aes(label = labels), hjust = 0.5, fontface = "bold", size = 4, family = "Georgia", color = "white", position = position_stack(vjust = 0.5)) +
  ggtitle("\nU.S. Energy Sources as a Percent of Production\n(among major sources) over time") +
  labs(caption = "\nSource: U.S. Energy Information Administration | github: julia-tache") +
  theme(plot.background = element_rect(fill = "#F5F5F5", color = NA),
        plot.margin = margin(0.25, 0.25, 0.25, 0.6, "cm"),
        panel.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.grid.major = element_line(color = "#F5F5F5"),
        panel.grid.minor = element_line(color = "#F5F5F5"),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 15, hjust = 0.5, face = "italic"),
        plot.caption = element_text(size = 12, face = "italic", hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 14, hjust = 0),
        axis.ticks = element_blank(),
        legend.position = "right",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "#F5F5F5"),
        text = element_text(family = "Georgia", size = 13))

ggsave("energy_production_us.png", height = 5, width = 8)


```


